name: Update Date in README

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Date
        run: |
          DATE=$(date '+%Y-%m-%d')
          sed -i "s/\\[Last Updated\\]: .*$/[Last Updated]: $DATE/" README.md
          git config user.email "ojw1912@gmail.com"
          git config user.name "Theo"
          git diff-index --quiet HEAD || git commit -am "Automatically update date in README" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git push
