name: Update README Date and D+

on:
  schedule:
    - cron: '15 15 * * *'  # 한국 시간 오전 12시(UTC 기준 오후 3시)
  workflow_dispatch:

jobs:
  update-readme-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config user.email "ojw1912@gmail.com"
          git config user.name "Theo"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
      - name: Calculate D+XXX and Format Date
        run: |
          # 오늘 날짜 계산
          TODAY=$(date '+%d %b %Y')

          # 기준일 계산
          START_DATE="2024-10-07"
          START_SECONDS=$(date -d $START_DATE +%s)
          TODAY_SECONDS=$(date +%s)

          # 날짜 차이 계산 (D+XXX)
          DIFF_DAYS=$(( (TODAY_SECONDS - START_SECONDS) / 86400 ))

          # 날짜 포맷 지정
          DATE=$(date '+%d %b %Y')
          DAY=$(echo $DATE | awk '{print $1}')
          MONTH=$(echo $DATE | awk '{print $2}')
          YEAR=$(echo $DATE | awk '{print $3}')

          # 날짜 접미사 처리 (st, nd, rd, th)
          if [[ $DAY == "01" || $DAY == "21" || $DAY == "31" ]]; then
            SUFFIX="st"
          elif [[ $DAY == "02" || $DAY == "22" ]]; then
            SUFFIX="nd"
          elif [[ $DAY == "03" || $DAY == "23" ]]; then
            SUFFIX="rd"
          else
            SUFFIX="th"
          fi

          DAY=$(echo $DAY | sed 's/^0//')$SUFFIX
          FORMATTED_DATE="$MONTH $DAY $YEAR"

          # README 파일 업데이트
          sed -i "s/\+!@#*/\+$DIFF_DAYS/" README.md
          sed -i "s/📅TODAY :.*$/📅TODAY : $FORMATTED_DATE/" README.md

          # 변경 사항 커밋
          git add README.md
          git commit -m "Update D+ and last updated date in README" || echo "Nothing to commit"
          git push
